#@ load("@ytt:data", "data")

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routecontroller
  namespace: #@ data.values.systemNamespace
rules:
- apiGroups: ["networking.cloudfoundry.org"]
  resources: ["routes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
